server:
  port: 8082
spring:
  application:
    name: adtradingservice
#  security:       
#    user:
#      name: adstradingservice
#      password: welcome1
      
  messages:
    basename: messages
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/acheteradstradingservicedb
    username: root
    password: root
  jpa:
    generate-ddl: false
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
feign:
  client:
    config:
      default:
        logger-level: full
              
springdoc:
  api-docs:
    path: /apidoc
  swagger-ui:
    path: /swagger-ui.html
    
notification:
  apiURL: http://localhost:8878    
  fromAddress: noreply@acheter.com
  
acheter:
  customer:
    baseURL: http://localhost:8080     
    
razorPayService:
  url: https://api.razorpay.com
  
  
logging:
  level:
    root: INFO
    '[com.acheter.adtradingservice]': debug
  file:
    path: /var/log/acheter/
    name: ${logging.file.path}/adtradingservice.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} - [%thread] - %-5level - %logger{36} - %msg%n"
    
    
    
    
    
    
